// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Pavlo Hrishyn",
            "email": "pashagrishyn@gmail.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app/info": {
            "get": {
                "description": "get app version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App"
                ],
                "summary": "returns current application's version",
                "responses": {
                    "200": {}
                }
            }
        },
        "/liquidity": {
            "get": {
                "description": "returns 5 latest liquidities",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Liquidity"
                ],
                "summary": "returns 5 latest liquidities",
                "responses": {
                    "200": {}
                }
            }
        },
        "/liquidity/:provider": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "saves in database new record and sets it in cache",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Liquidity"
                ],
                "summary": "creates new liquidity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "provider",
                        "name": ":provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "liquidity",
                        "name": "liquidity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/liquidity.Liquidance"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/liquidity/latest": {
            "get": {
                "description": "returns 5 latest liquidities",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Liquidity"
                ],
                "summary": "returns latest liquidities",
                "responses": {
                    "200": {}
                }
            }
        }
    },
    "definitions": {
        "liquidity.Liquidance": {
            "type": "object",
            "required": [
                "btc",
                "eur",
                "usd"
            ],
            "properties": {
                "btc": {
                    "type": "number"
                },
                "eur": {
                    "type": "number"
                },
                "usd": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "localhost:4421",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "fluent liquidity mapper v1.0",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
